---
# mongodb install playbook

- name: 'add mongodb repo key'
  sudo: 'yes'
  apt_key:
    keyserver: 'hkp://keyserver.ubuntu.com:80'
    id: '7F0CEB10'
    state: 'present'
  tags: '[mongodb]'

- name: 'add mongodb repo'
  sudo: 'yes'
  apt_repository:  
    repo: 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' 
    update_cache: 'yes'
    state: 'present'
  tags: '[mongodb]'

- name: 'install mongodb packages'
  sudo: 'yes'
  apt: 
    name: 'mongodb-org'
    update_cache: 'true'
    state: 'present'
#
#  ---> custom packages install looks similar to this:
#
#  action: apt update_cache=yes pkg={{item}} state=latest
#  with_items:
#    - mongodb-org-server
#    - mongodb-org-mongos
#    - mongodb-org-shell
#    - mongodb-org-tools
#
  tags: '[mongodb]'
  notify: – setup mongodb service